[repository]
name = "hyprXPrimary"
authors = ["Zakk"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "058fef2decc91a0849c7556a0ec428fe45a4d418"],
	["84ab8d11e8951a6551d1e1bf87796a8589da6d47", "ba7378e9bfa6adef1f4d7f7beeec0dbd9826d952"],
	["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "21590d6e832d8ba526cea385a847951258ec465a"],
	["19c90048d65a5660384d2fb865926a366696d6be", "701f7d78324cd6e0e3e35ab1dce78bb6e2879d29"],
	["c5e28ebcfe00a510922779b2c568cfa52a317445", "2ba94913ca02382d6e7eb4e96f41424ae6e80308"],
	["3875679755014997776e091ff8903acfb311dd2f", "f238216d93d2d2d9aae04e9f6286a413653c50d8"]
]


[hyprXPrimary]
description = "Primary XWayland display"
authors = ["Zakk"]
output = "hyprXPrimary.so"
build = [
	"make all"
]
